### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by zhangtag** [rowfishjs/rowfish#3]
`yarn run build`报错如下
`[ERROR] Docusaurus server-side rendering could not render static page with path /works.

TypeError: Cannot read properties of undefined (reading 'map')

[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at C:\Users\zhang\Desktop\web\node_modules\@docusaurus\core\lib\webpack\utils.js:180:24
    at C:\Users\zhang\Desktop\web\node_modules\webpack\lib\MultiCompiler.js:554:14
    at processQueueWorker (C:\Users\zhang\Desktop\web\node_modules\webpack\lib\MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
小白，望大佬解答

**Comment by ysicing** [comment]
应该是data/site/common.tsx 少了 

```ts
export const badges: Techbadge[] = [];
```

**Comment by zhangtag** [comment]
> 应该是data/site/common.tsx 少了
> 
> ```ts
> export const badges: Techbadge[] = [];
> ```

确实如此，感谢大佬解答！
